README.md
package-lock.json
package.json

Create file structure and add files, add README template, and add npm packages

add file structure and npm packages

---

config/connection.js
db/schema.sql

Adding schema.sql boilerplate for travel_db

schema.sql boilerplate

---

models/User.js

add User model

---

config/connection.js
controllers/index.js
package-lock.json
package.json
server.js

Change home-routes to homeRoutes in index.js controller file.

fix homeRoutes in index.js

---

controllers/api/index.js
controllers/index.js

added routes and middleware to /api/index.js file and updated name from postRoutes to tripRoutes; updated dashboard-routes to dashboardRoutes in index.js file

Tm fix index.js controllers file

---

controllers/api/commentRoutes.js
controllers/api/index.js
controllers/api/tripRoutes.js
controllers/api/userRoutes.js
controllers/dashboardRoutes.js
controllers/homeRoutes.js

fixed files based on errors received when trying to start server.

play whack a mole to start server based on errors

---

controllers/homeRoutes.js

just changing post to trips in homeRoutes.js so not confusing in the futures

changing 'post' to trips in homeRoutes.js

---

controllers/api/userRoutes.js

Complete the post routes in the userRoutes file

Tm user routes

---

controllers/multerRoutes.js
package-lock.json
package.json
server.js

multer routes

---

controllers/index.js
controllers/multerRoutes.js
package-lock.json
package.json
server.js
views/upload.handlebars

added routes to index.js, multerRoutes.js

Feature/multer index.js

---

controllers/multerRoutes.js
package-lock.json
package.json
server.js
views/upload.handlebars

upload.handlebars

---

models/Daily.js
views/login.handlebars
views/register.handlebars

login and register handlebar files: Made first letter in login and register file uppercase and added colons to match register

Tm dailylogmodel

---

package.json

start seed ability in package.json

---

views/login.handlebars

changed #username-register etc....

correcting non unique ids

---

.vscode/launch.json
controllers/api/index.js
controllers/api/userRoutes.js
models/User.js
public/js/login.js
views/login.handlebars

changed html for type=register to type=bug in login.handlebars

type=register bug resolution

---

controllers/dashboardRoutes.js
public/js/login.js
views/dashboard.handlebars

just trying to get routes working.  added dashboard.handlebars and put buttons to add a trip or look into a specific trip

after login go to /dashboard, page at render shows 'DASHBOARD'

---

controllers/api/dailyRoutes.js
controllers/api/index.js

1. Update api/index.js to add daily routes
2. add post request to dailyRoutes js file

Tm daily routes

---

models/Index.Js

-Added required Daily model to file
-Added two associations for Daily (belongs to trip & trip has many daily)
-rearranged file so all belongs to and has many are grouped together

update models/index.js to add associations for the daily logs

---

public/js/add-trip.js
public/js/comment.js
public/js/delete-trip.js
public/js/edit-trip.js
public/js/login.js
public/js/signup.js

I will update Javascript files in this branch.

Jw public js update

---

models/Image.js
models/Index.Js

In Index.js, the Image model belongs to Daily model thru the foreign key 'daily_id'.  I don't know if that will be the final connection, just trying to get the image to upload to database and connect somewhere.  We can change it whenever to whatever makes sense

created Image model, added it to Index.js

---

controllers/api/index.js
controllers/dashboardRoutes.js
views/edit-trip.handlebars

- Add dailyroutes and trip routes back into the api/index.js file and remove jw comments - these routes are needed for the daily log and for the adding trip
- remove extra / after create GET route, change trip_content to trip_description to match model

Tm resolving errors after pull request

---

controllers/api/index.js
controllers/api/tripRoutes.js
controllers/api/userRoutes.js
controllers/dashboardRoutes.js
public/js/add-trip.js
public/js/edit-trip.js
views/create-trip.handlebars
views/edit-trip.handlebars

Creating a trip was causing an error so these updates were made to resolve that error.
1. edit-trip and create-trip handlebars files were updated to change the name of values, and fields to match the new Trip model - This has been tested and everything pulls correctly.  Create trip works, but the edit button does not yet work.  Will try to resolve that in another pull request. 
2. I updated the public add-trip and edit trip files to change the field names to match the trip model
3. TripRoutes file was also updated to change the field names to match the trip model

Tm update create trip to resolve error

---

controllers/multerRoutes.js
models/Image.js
models/Index.Js
server.js

It doesn't break anything and it still saves the picture to the images directory but just won't populate the image table.  But thats all that needs to happen

uploader connects to DB, sort of

---

views/homepage.handlebars

just surrounded homepage.handlebars in a href='/login'.  now I'm going to put a link on the login page that links to the registration page

Linked homepage trips to login page

---

public/js/edit-trip.js
views/edit-trip.handlebars

haven't fixed delete but when you hit save button in edit the changes register and user is sent back to trips page.

changed script src in edit-trip.hbs from post to trip

---

public/css/style.css
views/add.handlebars
views/create-trip.handlebars
views/daily.handlebars
views/dashboard.handlebars
views/edit-trip.handlebars
views/layouts/main.handlebars
views/login.handlebars
views/signup.handlebars
views/single-trip.handlebars

-use bulma styling for all buttons
-add styling to allow for spacing between elements

style buttons and add margin to allow for spacing

---

public/js/add-daily.js
views/dashboard.handlebars
views/partials/trip-details.handlebars
views/partials/trip-info.handlebars

fix create button

---

public/css/style.css
views/layouts/main.handlebars

Changed title of page from travel blog to Wanderlust
-piggybacked off jungwoo's styling to add additional color and font
-remove not needed google font file I added to main handlebars file

Tm edit title of page

---

controllers/multerRoutes.js

just making sure the updated multer routes are included.  they will need to be adjusted to conform to new routing structures

the multer routes file that worked after working with Torre

---

models/Image.js

just added those two references just in case, i don't know exactly how it is going to link to either trip page or daily page

added a daily_id and trip_id as reference models for Image model

---

public/css/style.css
views/add-daily-info.handlebars

on add-daily-info.hbs
margin for the row that has stuff about uploading

added styling so buttons have space in between on small screens

---

README.md
controllers/api/dailyRoutes.js
views/add-daily-info.handlebars
views/partials/splashpage.handlebars

included is some small alterations to the dailyRoutes and add-daily-info.hbs but they shouldn't break anything

delete splashpage, couple readme additions

---

public/css/style.css
views/login.handlebars
views/partials/comments.handlebars
views/partials/navbar.handlebars
views/signup.handlebars
views/single-trip.handlebars

Cleanup responsive issues on comments page, update button styling, update styling on login and register page.

Tm resolve responsive issues
